---
# This section defines a ClusterIssuer for self-signed 
# certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# This section requests a self-signed certificate 
# from the ClusterIssuer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: <CERT-NS>
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# This section configures an Issuer to respond to 
# certificate requests using the self-signed CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: <CERT-NS>
spec:
  ca:
    secretName: root-secret
---
# This section configures an Ingress to request 
# a certificate from the specified Issuer
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <INGRESS NAME>
  namespace: <CERT-NS>
  annotations:
    cert-manager.io/issuer: my-ca-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - <FQDN/HOSTNAME>
      secretName: <INSERT CERTIFICATE NAME HERE>
  rules:
    - host: <FQDN/HOSTNAME>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <TARGET APP>
                port:
                  number: 80
